### ISSUE TITLE
Syntax HighLighting for Syncmapping

### ISSUE THREAD

**Issue by alexgravelvid** [cdpautsch/vscode-tpl#19] opened 2020-01-06 20:18 UTC
I am writing a "synmapping block" (not pattern) and the syntax doesn't seem to highlight properly.
The first lines seem to be good. but when i open the "block" syncmapping, the highlight doesn't seem to work. Only the comments seem to work
## Expected Behavior

The TPL keyword should be in a color scheme
## Current Behavior

No Colors on TPL Keywords in the syncmapping block
## Steps to Reproduce or Example

You can use this TPL to tryout :)

tpl 1.5 module CMDB.Extension.Host.Windows;

metadata
		origin := 'COM';
		tree_path := 'COM','CMDB', 'Service', 'Host','Windows';
end metadata;

from CMDB.Host_ComputerSystem import Host_ComputerSystem 2.0;

syncmapping COM_Service_Host_Windows 1.0
    """
    Relate Server with its Hosting Service
    """
    overview
        tags COM, CMDB, Extension, Service;
    end overview;
	
	constants
		SB_Name  := "@SERVICE_NAME@";
	end constants;

    mapping from Host_ComputerSystem.host where os_type = "Windows" as host
	
			SB_service -> BMC_BusinessService;
			
    end mapping;

    body
		
		computersystem := Host_ComputerSystem.computersystem;
		key := text.hash(SB_Name);
		SB_service := sync.shared.BMC_BusinessService(
			key              := key,
			Name             := SB_Name,
			ServiceType		 := 20
		);
            log.debug("COM: Relate %SB_Name% with %computersystem.name%");
            // Relate the BMC_ComputerSystem to the new BMC_BusinessService
            sync.rel.BMC_Component(
                Source      := computersystem,
                Destination := SB_service,
                Name        := "COMPONENT"
            );
            

    end body;

end syncmapping;

## Other Information (optional)

Add the same color scheme as for "pattern" Block

**Comment by cdpautsch** [comment] 2020-03-28 04:17
Apologies for the late reply. Strangely, I never received a notification.

I haven't had any time to maintain this, but I will work on taking a closer look and see what I can do.

**Comment by cdpautsch** [comment] 2020-03-28 14:15
Confirmed: syntax highlighting not working as expected

![image](https://user-images.githubusercontent.com/28664455/77824978-c8ab3180-70dc-11ea-90ae-d0d6034a0c3d.png)

I believe it's because the syncmapping block isn't properly recognized as a code block. The syntax highlighting works by identifying blocks and then highlighting its contents.

**Comment by cdpautsch** [comment] 2020-03-28 15:05
I am working on updating highlighting for `sync` functions such as `sync.rel` and `sync.shared`. I'm less familiar with the syntax; is there an example of all possible `sync.rel`/`sync.shared` namespaces? e.g. `BMC_Component`, `BMC_BusinessService`, etc?

**Comment by cdpautsch** [comment] 2020-03-28 15:14
Gonna close this, as basic syncmapping IS supported.

It still needs work, however. I'm going to capture all enhancement work (such as my question above) in #21

**Closed as completed by cdpautsch** 2020-03-28 15:14 UTC
Labels: bug

**Comment by alexgravelvid** [comment] 2020-03-30 12:56
Hi, I believe most of the name space can be found in Administration (cog wheel) -> CMDB Sync -> Choose CMDB Sync Connexion -> Filtering -> CMDB . List should be in the drop down named : CMDB CI type to filter. Although there are more Type that can be added manually e.g. BMC_BusinessService. But most will be there. Thanks !

**Comment by cdpautsch** [comment] 2020-03-30 20:48
Unfortunately I don't have access to a BMC system with a CMDB Sync Connection at present. I don't suppose you could provide a screenshot or printout of the options?

Or perhaps, simpler still, will they _ALWAYS_ follow the `BMC_<something>` pattern? Are there any restrictions on what that `<something>` can be?

**Comment by alexgravelvid** [comment] 2020-04-03 12:38
I think it would be a safe rule to follow. I know it is possible to create custom CMDB class, although I don't know if we can use them in Discovery in order to sync CIs in those custom class. 
I found to class that doesn't match the exact pattern though :
BMC.MAINFRAME:BMC_StorageSubsystem
BMC.MAINFRAME:BMC_MFCouplingFacility
All the other one starts with BMC_%
Sorry for late reply !
